const tableName = "measurement_logs";

const seed = async function (knex) {
  await knex(tableName).truncate();
  await knex(tableName).insert([
    {
      user_id: 1,
      sub_id: 1,
      measured_at: "2025-05-27 10:15:32",
      measurements: JSON.stringify({
        freeChlorine: 0.5,
        freeChlorine_depo: 0.5,
        totalChlorine: 0.7,
        combinedChlorine: 0.2,
        pH: 7.8,
        pH_depo: 7.8,
        temperature: 22.5,
        salinity: 35.1,
        totalColiforms: 100,
        eColi: 100,
      }),
      comment: "Morning measurements",
      comment_type: "observation",
    },
    {
      user_id: 2,
      sub_id: 3,
      measured_at: "2025-05-27 14:30:00",
      measurements: JSON.stringify({
        freeChlorine: 0.5,
        freeChlorine_depo: 0.5,
        totalChlorine: 0.7,
        combinedChlorine: 0.2,
        pH: 7.8,
        pH_depo: 7.8,
        temperature: 22.5,
        salinity: 35.1,
        totalColiforms: 100,
        eColi: 100,
      }),
      comment: "Afternoon check",
      comment_type: "observation",
    },
    {
      user_id: 2,
      sub_id: 3,
      measured_at: "2025-05-27 14:30:00",
      measurements: JSON.stringify({
        freeChlorine: 0.6,
        freeChlorine_depo: 0.6,
        totalChlorine: 0.8,
        combinedChlorine: 0.2,
        pH: 7.9,
        pH_depo: 7.9,
        temperature: 23.1,
        salinity: 35.0,
        totalColiforms: 100,
        eColi: 100,
      }),
      comment: "Afternoon check",
      comment_type: "observation",
    },
    {
      user_id: 1,
      sub_id: 2,
      measured_at: "2025-05-28 09:00:00",
      measurements: JSON.stringify({
        freeChlorine: 0.4,
        freeChlorine_depo: 0.4,
        totalChlorine: 0.6,
        combinedChlorine: 0.2,
        pH: 7.7,
        pH_depo: 7.7,
        temperature: 21.9,
        salinity: 35.2,
        totalColiforms: 300,
        eColi: 200,
      }),
    },
    {
      user_id: 3,
      sub_id: 5,
      measured_at: "2025-05-26 16:00:45",
      measurements: JSON.stringify({
        freeChlorine: 0.55,
        freeChlorine_depo: 0.55,
        totalChlorine: 0.75,
        combinedChlorine: 0.2,
        pH: 7.85,
        pH_depo: 7.85,
        temperature: 22.8,
        salinity: 35.15,
        totalColiforms: 200,
        eColi: 150,
      }),
      comment: "Sample from quarantine",
      comment_type: "other",
    },
    {
      user_id: 2,
      sub_id: 1,
      measured_at: "2025-04-15 08:30:00",
      measurements: JSON.stringify({
        freeChlorine: 0.5,
        freeChlorine_depo: 0.5,
        totalChlorine: 0.9,
        combinedChlorine: 0.4,
        pH: 7.3,
        pH_depo: 7.3,
        temperature: 22.1,
        salinity: 34.8,
        totalColiforms: 250,
        eColi: 150,
      }),
      comment: "Total chlorine elevated",
      comment_type: "error",
    },
    {
      user_id: 4,
      sub_id: 3,
      measured_at: "2025-04-18 14:15:00",
      measurements: JSON.stringify({
        freeChlorine: 0.45,
        freeChlorine_depo: 0.45,
        totalChlorine: 0.65,
        combinedChlorine: 0.2,
        pH: 7.4,
        pH_depo: 7.4,
        temperature: 23.1,
        salinity: 34.8,
        totalColiforms: 150,
        eColi: 80,
      }),
      comment: "",
      comment_type: null,
    },
    {
      user_id: 1,
      sub_id: 4,
      measured_at: "2025-04-22 11:45:00",
      measurements: JSON.stringify({
        freeChlorine: 0.6,
        freeChlorine_depo: 0.6,
        totalChlorine: 0.75,
        combinedChlorine: 0.15,
        pH: 8.6,
        pH_depo: 8.6,
        temperature: 24.2,
        salinity: 35.1,
        totalColiforms: 120,
        eColi: 80,
      }),
      comment: "pH running high",
      comment_type: "observation",
    },
    {
      user_id: 5,
      sub_id: 2,
      measured_at: "2025-04-25 09:20:00",
      measurements: JSON.stringify({
        freeChlorine: 0.52,
        freeChlorine_depo: 0.52,
        totalChlorine: 0.72,
        combinedChlorine: 0.2,
        pH: 7.6,
        pH_depo: 7.6,
        temperature: 22.0,
        salinity: 35.3,
        totalColiforms: 800,
        eColi: 400,
      }),
      comment: "",
      comment_type: null,
    },
    {
      user_id: 3,
      sub_id: 6,
      measured_at: "2025-05-02 16:30:00",
      measurements: JSON.stringify({
        freeChlorine: 0.45,
        freeChlorine_depo: 0.45,
        totalChlorine: 0.65,
        combinedChlorine: 0.2,
        pH: 7.0,
        pH_depo: 7.0,
        temperature: 23.5,
        salinity: 34.8,
        totalColiforms: 450,
        eColi: 280,
      }),
      comment: "pH slightly low",
      comment_type: "error",
    },
    {
      user_id: 2,
      sub_id: 7,
      measured_at: "2025-05-05 13:10:00",
      measurements: JSON.stringify({
        freeChlorine: 0.65,
        freeChlorine_depo: 0.65,
        totalChlorine: 0.78,
        combinedChlorine: 0.13,
        pH: 7.8,
        pH_depo: 7.8,
        temperature: 24.5,
        salinity: 35.0,
        totalColiforms: 120,
        eColi: 90,
      }),
      comment: "Systems operating normally",
      comment_type: "observation",
    },
    {
      user_id: 4,
      sub_id: 8,
      measured_at: "2025-05-08 10:00:00",
      measurements: JSON.stringify({
        freeChlorine: 0.48,
        freeChlorine_depo: 0.48,
        totalChlorine: 0.68,
        combinedChlorine: 0.2,
        pH: 7.5,
        pH_depo: 7.5,
        temperature: 13.2,
        salinity: 34.5,
        totalColiforms: 320,
        eColi: 180,
      }),
      comment: "Temperature running low",
      comment_type: "other",
    },
    {
      user_id: 1,
      sub_id: 1,
      measured_at: "2025-05-12 15:45:00",
      measurements: JSON.stringify({
        freeChlorine: 0.58,
        freeChlorine_depo: 0.58,
        totalChlorine: 0.73,
        combinedChlorine: 0.15,
        pH: 7.3,
        pH_depo: 7.3,
        temperature: 25.8,
        salinity: 36.2,
        totalColiforms: 300,
        eColi: 180,
      }),
      comment: "Routine check completed",
      comment_type: "observation",
    },
    {
      user_id: 6,
      sub_id: 4,
      measured_at: "2025-05-15 12:30:00",
      measurements: JSON.stringify({
        freeChlorine: 0.52,
        freeChlorine_depo: 0.52,
        totalChlorine: 0.72,
        combinedChlorine: 0.2,
        pH: 7.4,
        pH_depo: 7.4,
        temperature: 32.1,
        salinity: 35.8,
        totalColiforms: 380,
        eColi: 220,
      }),
      comment: "Temperature elevated",
      comment_type: "error",
    },
    {
      user_id: 2,
      sub_id: 3,
      measured_at: "2025-05-18 08:15:00",
      measurements: JSON.stringify({
        freeChlorine: 0.51,
        freeChlorine_depo: 0.51,
        totalChlorine: 0.69,
        combinedChlorine: 0.18,
        pH: 7.7,
        pH_depo: 7.7,
        temperature: 23.4,
        salinity: 34.5,
        totalColiforms: 220,
        eColi: 130,
      }),
      comment: "",
      comment_type: null,
    },
    {
      user_id: 5,
      sub_id: 5,
      measured_at: "2025-05-22 17:20:00",
      measurements: JSON.stringify({
        freeChlorine: 0.38,
        freeChlorine_depo: 0.38,
        totalChlorine: 0.58,
        combinedChlorine: 0.2,
        pH: 7.1,
        pH_depo: 7.1,
        temperature: 20.8,
        salinity: 29.5,
        totalColiforms: 680,
        eColi: 320,
      }),
      comment: "pH slightly acidic",
      comment_type: "observation",
    },
    {
      user_id: 3,
      sub_id: 2,
      measured_at: "2025-05-25 11:00:00",
      measurements: JSON.stringify({
        freeChlorine: 0.62,
        freeChlorine_depo: 0.62,
        totalChlorine: 0.76,
        combinedChlorine: 0.14,
        pH: 8.1,
        pH_depo: 8.1,
        temperature: 26.3,
        salinity: 37.1,
        totalColiforms: 85,
        eColi: 45,
      }),
      comment: "",
      comment_type: null,
    },
    {
      user_id: 4,
      sub_id: 7,
      measured_at: "2025-05-29 14:50:00",
      measurements: JSON.stringify({
        freeChlorine: 0.47,
        freeChlorine_depo: 0.47,
        totalChlorine: 0.67,
        combinedChlorine: 0.2,
        pH: 7.9,
        pH_depo: 7.9,
        temperature: 24.1,
        salinity: 35.8,
        totalColiforms: 410,
        eColi: 250,
      }),
      comment: "End of month reading",
      comment_type: "other",
    },
    {
      user_id: 1,
      sub_id: 8,
      measured_at: "2025-06-01 09:30:00",
      measurements: JSON.stringify({
        freeChlorine: 0.44,
        freeChlorine_depo: 0.44,
        totalChlorine: 0.64,
        combinedChlorine: 0.2,
        pH: 7.5,
        pH_depo: 7.5,
        temperature: 22.7,
        salinity: 34.2,
        totalColiforms: 350,
        eColi: 190,
      }),
      comment: "",
      comment_type: null,
    },
  ]);
};

export { seed };
